### ISSUE TITLE
Babel error

### ISSUE THREAD

**Issue by kcmr** [kcmr/vsce-remove-unused-imports#18]
Hey!
Thanks a lot for your work.
I'm having a weird message in my vscode project and this does not seem to work because of that : 

```
[BABEL] unknown: Preset your preset  requires a filename to be set when babel is called directly,

babel.transform(code, { filename: 'file.ts', presets: [/* your preset */] });

See https://babeljs.io/docs/en/options#filename for more information.
```

Any ideas? Am i missing something here?

_Originally posted by @Kowaio in https://github.com/kcmr/vsce-remove-unused-imports/issues/5#issuecomment-1216587185_

**Comment by Kowaio** [comment]
> Hi @Kowaio

> I've created a new issue for this, as this one is closed and it doesn't seem to be related to this one.
Can you please share more information https://github.com/kcmr/vsce-remove-unused-imports/issues/18 about the context in which the error happens? The file that you are editing, etc.

Hey @kcmr 
Thanks for your reply.
About the issue, it's just that I installed the extension and added the line in my vscode settings.json as said in the readme but now, when i'm saving any file, I got a popup window that says the error message above.

[https://imgur.com/a/xkpX7N4](url)

My babel config.js is mostly empty in my React Native project (.js files)

`
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['react-native-reanimated/plugin'],
}
`

**Comment by kcmr** [comment]
I don't think the issue you are describing is related to this extension. Can you try disabling the extension, relaunching Code and saving the file again to check if the popup appears?

**Comment by Kowaio** [comment]
Yes of course, I already tried it, uninstalled it and this doesn't occur.

**Comment by Kowaio** [comment]
I also don't get the message if I remove this from settings.json
`  "editor.codeActionsOnSave": {
    "source.removeUnusedImports": true
  },`

**Comment by kcmr** [comment]
Can you share with me the project where you are experiencing this? Otherwise, an isolated part of the project where the error can be reproduced (the file, you babel config, etc.). I can't get it to reproduce the error.

**Comment by Kowaio** [comment]
I won't be able unfortunately as it's a company project.
Maybe it's coming from a babel version i have installed? I'll try and find why it's doing that.
Thanks

**Comment by kcmr** [comment]
I don't know… My thinking is another extension is transforming the code on save before this one, but I have no idea. Please, let me know if you find something.

**Comment by Kowaio** [comment]
Sure!

I might have found a thread where it was ocurring on i18n-extract lib.

Here's the commit that fixes the problem, maybe if you see something relevant:

https://github.com/skt-t1-byungi/i18n-extract/commit/00627ed1d8896def07c6e6d490e7d9062942241c

I'll keep digging

**Comment by Kowaio** [comment]
Ok found it!

I removed the `module:metro-react-native-babel-preset` in my babel config.js as seen above and it worked. Unfortunately I still need to use this preset in my project. I'll see how to manage the two of them, maybe by adding this `filename` param that is needed. I don't know a lot about babel so the time to learn is now.
Thanks

**Comment by kcmr** [comment]
Glad that you found the problem :) 

I'm closing the issue for now as I'm not sure if is related to the extension and I don't have enough information to reproduce it. If you can isolate the problem in a single file or example repository, I'll can take a look.

Thanks

**Comment by Kowaio** [comment]
Yes, I don't really know if it is related or not, but another lib linked below or here : https://github.com/oliviertassinari/i18n-extract/issues/67 had this issue and fixed it by adding 'filename' in babel transform calls (to prevent this for happening). I think only people using `metro-react-native-babel-preset` will run this issue. Maybe you can set up a react native projet using this preset to reproduce it? Maybe it will help.
Thanks anyway for your lib!
Cheers
