### ISSUE TITLE
Extension removes some Angular imports

### ISSUE THREAD

**Issue by geksonES** [kcmr/vsce-remove-unused-imports#20]
It removes Inject and MAT_DIALOG_DATA that goes into constructor

```
import { Component, Inject } from '@angular/core';
import { MAT_DIALOG_DATA } from '@angular/material/dialog';


@Component({
  template: '',
  styles: ['']
})
export class SomeComponent {
  constructor(
    @Inject(MAT_DIALOG_DATA)
    public dialogData
  ) { }
}

**Comment by ShtibsIdeo** [comment]
It's also happening to me

**Comment by vturbin** [comment]
Yes I noticed too when imports are in the constructor, such as @Inject or forwardRef, imports are not recognized and removed for some reason. Happens to me as well. Hope it can be solved soon
    public constructor(
        private notificationRequestService: NotificationRequestService,
        @Inject(forwardRef(() => TestRunService))
)

**Comment by NurimOnsemiro** [comment]
It happens to me too.
I'm using the tsyringe module, and despite using @inject() in the constructor parameter, the imported module is automatically deleted the moment I save.
I look forward to seeing this issue resolved.

**Comment by rschuster84** [comment]
This is what happens with all these:
- Inject
- Host
- SkipSelf
- Optional
- Self

I don't think the list is complete though.
