### ISSUE TITLE
Could you add a setting that makes this happen automatically on save, like prettify? thanks!!

### ISSUE THREAD

**Issue by RheingoldRiver** [kcmr/vsce-remove-unused-imports#23]

**Comment by kcmr** [comment]
Hi @RheingoldRiver 

That feature is already available as a code action. It's [documented here](https://github.com/kcmr/vsce-remove-unused-imports#run-on-save).

You need to add this in your settings:
```
"editor.codeActionsOnSave": {
  "source.removeUnusedImports": true
}
```

Thanks for using it!

**Comment by RheingoldRiver** [comment]
Oh wow, idk how I missed that in the readme. Thanks!!
