### ISSUE TITLE
Support Typescript 4.9.4+

### ISSUE THREAD

**Issue by spilist** [kcmr/vsce-remove-unused-imports#24]
Thx for the great extension, I love it.

Recently I experienced [this issue](https://stackoverflow.com/questions/75002858/vscode-shows-an-error-message-when-satisfies-keyword-is-used) and found out the reasons was this package.

I forked this repository, upgraded all packages to latest, published to vscode marketplace, and confirmed the upgraded version  worked well. (https://marketplace.visualstudio.com/items?itemName=spilist.remove-unused-imports-ts-494)

You can refer to https://github.com/spilist/vsce-remove-unused-imports/commit/2a4750e5a85708586eaa3eaf43537ba347d86c5d what I changed. When you update the package, I'll remove mine.

**Comment by kcmr** [comment]
Hi @spilist 

Thank you for the investigation. 
I will take a look later and try to release a version with updated dependencies.

**Comment by kcmr** [comment]
Hi @spilist 

Version 1.2.3 with updated TS dependencies is already published: https://marketplace.visualstudio.com/items?itemName=kuscamara.remove-unused-imports

Thank you for the help :)

**Comment by spilist** [comment]
@kcmr Thank you!
