### ISSUE TITLE
Doesn't work at annotation

### ISSUE THREAD

**Issue by ggggmlor** [kcmr/vsce-remove-unused-imports#3]
Platfom: Windows

Problem: It seems that it doesn't work with annotation in a .ts file

Snapshot:
![image](https://user-images.githubusercontent.com/29994266/155914228-c327ce7b-4f31-4d5c-a43c-00ecfb90e79d.png)

**Comment by kcmr** [comment]
Hi @ggggmlor 

Thank you for reporting the issue. I'll try to look at it during this week.

**Comment by kcmr** [comment]
Hi @ggggmlor 

The last version of the extension ([1.0.6](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/kuscamara/vsextensions/remove-unused-imports/1.0.6/vspackage)) should be working with decorators.

Thanks
