### ISSUE TITLE
Questions: 1. run on save? 2. every file?

### ISSUE THREAD

**Issue by bigandy** [kcmr/vsce-remove-unused-imports#5]
I have a couple of questions: 

1. Is it possible to add an option to run on save (like [in step 3 of this article](https://www.linkedin.com/pulse/how-remove-unused-imports-vscode-kaleem-elahi))
2. is it possible to run on every file with one command?

**Comment by kcmr** [comment]
Hi @bigandy 

I can investigate the first option but I'm not sure the second would be possible. I don't remember any extension that allows formatting all the files in a workspace. For that, it would be better to use a npm-script. Something like the approach described in this article using ESLint: https://simondosda.github.io/posts/2021-05-10-eslint-imports.html

**Comment by JustinRohweller** [comment]
Thanks for making this extension, it's awesome. 
I was able to get it to run on save with https://marketplace.visualstudio.com/items?itemName=fsevenm.run-it-on
That being said, it always modifies the file, so it always results in an unsaved file.
Is there any way to have this extension do nothing if the imports are already correct?

**Comment by Kowaio** [comment]
hey!
Thanks for this extension. Upping this topic as it would be great to add it on save. I don't know if it's still in the works.
Thanks!

**Comment by kcmr** [comment]
Hi @Kowaio 

Yes, it would be a great feature, but in my opinion, only for the active editor (current edited file). Sadly, I don't have too much time to investigate and develop this at the moment, so any help with this would be appreciated. I'm keeping the issue open and tagging it with Help wanted.

Thank you all for using it and the suggestions.

**Comment by kcmr** [comment]
Hello everyone,

Finally, I got some time to develop this feature. It is **available in version 1.2.0** via Code Actions.

To enable it (in your VS Code settings):

```json
"editor.codeActionsOnSave": {
  "source.removeUnusedImports": true
}
```

I hope this helps :)
Please, leave the extension a rating if you find it useful. It is still unrated.

**Comment by Kowaio** [comment]
Hey!
Thanks a lot for your work.
I'm having a weird message in my vscode project and this does not seem to work because of that : 

```
[BABEL] unknown: Preset your preset  requires a filename to be set when babel is called directly,

babel.transform(code, { filename: 'file.ts', presets: [/* your preset */] });

See https://babeljs.io/docs/en/options#filename for more information.
```

Any ideas? Am i missing something here?

**Comment by kcmr** [comment]
> Hey! Thanks a lot for your work. I'm having a weird message in my vscode project and this does not seem to work because of that :
> 
> ```
> [BABEL] unknown: Preset your preset  requires a filename to be set when babel is called directly,
> 
> babel.transform(code, { filename: 'file.ts', presets: [/* your preset */] });
> 
> See https://babeljs.io/docs/en/options#filename for more information.
> ```
> 
> Any ideas? Am i missing something here?

Hi @Kowaio 

I've created a new issue for this, as this one is closed and it doesn't seem to be related to this one.
Can you please share more information [here](https://github.com/kcmr/vsce-remove-unused-imports/issues/18) about the context in which the error happens? The file that you are editing, etc.

Thanks
